# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8431812e6b119b5d6a614cf21a9c5ac5036882aadc15fe74ad59a9ba669e5255081691e41c0232c2c6124dfa42e04da7a92a975cf2dd15a2dfc75175c2b24f30

test:
  secret_key_base: 84d35da23a521a9077b1b34d2bdc0a480bba7fa35c5455a8a5add736e60c550e4abd7f973c3c0a02cc191554e111e0225b259863a6acd08381ce3aba2b061c19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
